
name: Open Website Daily
on:
  schedule:
    - cron: '30 13 * * *' # 7:00 PM IST
  workflow_dispatch:

jobs:
  open_url:
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright
        run: npm install playwright
      - name: Run Script
        env:
          MY_REPORT_KEY: ${{ secrets.MY_REPORT_KEY }}
          k2: ${{ secrets.ack }}
        run: node trigger.js
